
services:
  # Сервис пользователей (PostgreSQL)
  user-service-postgres:
    image: postgres:latest
    container_name: bookmaker-user-postgres
    environment:
      POSTGRES_DB: user_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "10000:5432"
    volumes:
      - user_pg_data:/var/lib/postgresql/data

  # Сервис спортивных данных (MongoDB)
  sportdata-service-mongodb:
    image: mongo:latest
    container_name: bookmaker-sportdata-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: sport_data
    ports:
      - "27017:27017"
    volumes:
      - sportdata_mongo_data:/data/db

volumes:
  user_pg_data:
  sportdata_mongo_data: